use strict;
use warnings;
$ENV{'XDG_SESSION_TYPE'} = 'tty';
$ENV{'DBUS_SESSION_BUS_ADDRESS'} = 'unix:path=/run/user/10015/bus';
$ENV{'MBNI_PROFILE'} = 'yes';
$ENV{'SSH_CONNECTION'} = '10.17.154.189 53110 192.168.0.26 22';
$ENV{'SGE_ROOT'} = '/opt/sge';
$ENV{'SGE_CLUSTER_NAME'} = 'mbni';
$ENV{'SGE_ARCH'} = 'lx-amd64';
$ENV{'LANG'} = 'en_US.UTF-8';
$ENV{'SSH_CLIENT'} = '10.17.154.189 53110 22';
$ENV{'SSH_TTY'} = '/dev/pts/0';
$ENV{'OLDPWD'} = '/garage/wilsonte_lab/bin/q';
$ENV{'SHELL'} = '/bin/bash';
$ENV{'XDG_RUNTIME_DIR'} = '/run/user/10015';
$ENV{'PATH'} = '/garage/wilsonte_lab/bin/R/R-3.6.0/bin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/local/sbin:/usr/local/bin:/usr/bin:/garage/hpc/bin:/garage/hpc/mbni-run-vm/bin:/garage/hpc/globusconnectpersonal-2.3.6:/garage/hpc/MATLAB/R2018b/bin:/garage/wilsonte_lab/bin/bbmap/bbmap_38.46:/garage/wilsonte_lab/bin/bedtools/bedtools_v2.28.0/bedtools2/bin:/garage/wilsonte_lab/bin/bowtie/bowtie2-2.3.3/bowtie2-2.3.3.1-linux-x86_64:/garage/wilsonte_lab/bin/htslib/htslib-1.9/htslib-1.9:/garage/wilsonte_lab/bin/pigz/pigz-2.4/pigz-2.4:/garage/wilsonte_lab/bin/samtools/samtools-1.9/samtools-1.9:/garage/wilsonte_lab/bin/STAR/STAR-2.7.0f/bin/Linux_x86_64:/garage/wilsonte_lab/bin/bwa/bwa-0.7.17:/garage/wilsonte_lab/bin/wilson-ware/msvtools-0.0.1:/garage/wilsonte_lab/bin/wilson-ware/svtools-0.0.1:/garage/wilsonte_lab/bin/wilson-ware/utilities/slurp:/garage/wilsonte_lab/bin/wilson-ware/utilities/smooth:/garage/wilsonte_lab/bin/wilson-ware/utilities/segment:/garage/wilsonte_lab/bin/wilson-ware/utilities/bedutil:/garage/wilsonte_lab/bin/q/q-pipeline-manager-develop:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl';
$ENV{'SHLVL'} = '1';
$ENV{'PWD'} = '/garage/wilsonte_lab/bin/q/q-pipeline-manager-develop';
$ENV{'TERM'} = 'xterm';
$ENV{'XDG_SESSION_CLASS'} = 'user';
$ENV{'XDG_SESSION_ID'} = '2017';
$ENV{'_'} = '/usr/bin/perl';
$ENV{'SGE_CELL'} = 'default';
1;
